"""job posting remote flag

Revision ID: 18efe4e45083
Revises: d5f3b2c8e014
Create Date: 2026-08-15 11:16:54.454146+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18efe4e45083'
down_revision: Union[str, Sequence[str], None] = 'd5f3b2c8e014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('remote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    # free backfill: the whole RemoteOK board is remote by definition. Scraped
    # rows stay NULL ("source didn't say") until cli.backfill_remote re-reads them.
    op.execute("UPDATE job_postings SET remote = true WHERE source = 'remoteok'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'remote')
    # ### end Alembic commands ###
